### ISSUE TITLE
Crash with Curios 4.0.5.1

### ISSUE THREAD

**Issue by azaquaz** [cech12/UsefulHats#41] opened 2021-04-29 22:01 UTC
Useful Hats version: 1.9.4
Despite saying it supports Curios 4.0.0.0 or later, crashes with 4.0.5.1
![image](https://user-images.githubusercontent.com/32604800/116623724-ac4b7b00-a914-11eb-8ed7-e6005e67c789.png)

**Comment by cech12** [comment] 2021-04-29 22:05
Weird?! This check is done by Forge, not by this mod... :/
I will look into this.

**Comment by cech12** [comment] 2021-04-29 22:06
Which Minecraft/Forge version are you using?

Maybe the change of Forge version 36.1.10 causes this error. Please test to downgrade to 36.1.9 as a workaround for now.

I will look deeper into this when I have time.

**Comment by azaquaz** [comment] 2021-04-29 22:28
I'm on Forge 36.1.13, downgrading to 36.1.9 does indeed fix it.

**Comment by cech12** [comment] 2021-04-30 17:00
Thanks for your report! The issue is fixed and released in version 1.9.5

**Closed as completed by cech12** 2021-04-30 17:00 UTC
Labels: bug
