### ISSUE TITLE
[Bug]: Mining Hat not working

### ISSUE THREAD

**Issue by Imperial-Warlord** [cech12/UsefulHats#62] opened 2024-07-08 05:10 UTC
### Minecraft Version

1.20.4

### Mod Loader

Fabric

### Mod Loader Version

Fabric 1.20.4

### Mod Version

1.20.4-5.1.3.0

### Modpack or other Mod

A pretty extensive modpack

https://modrinth.com/modpack/jadzcraft

### Describe the Issue

The Mining Hat makes you mine slower than without it.
To test this, I mined basalt straight down with an efficiency V diamond pickaxe for 15 seconds 5 different times

With the mining hat I averaged ~25 basalt, but without it I averaged ~36 basalt, making the mining hat actually slower than nothing.

**Comment by cech12** [comment] 2024-07-08 05:18
Thanks for your report! I will look into that, when I have time :)

**Comment by cech12** [comment] 2024-07-08 16:15
Thanks again for your report! The issue is fixed in the upcoming versions:
- 1.20.4-5.1.3.1
- 1.20.6-5.2.0.1
- 1.21-6.2.0.0

**Closed as completed by cech12** 2024-07-08 16:15 UTC
Labels: bug
