### ISSUE TITLE
[Bug]: Postman hat uses the wrong tag for crafting

### ISSUE THREAD

**Issue by WhitePhant0m** [cech12/UsefulHats#66] opened 2024-07-18 14:50 UTC
### Minecraft Version

1.21

### Mod Loader

NeoForge

### Mod Loader Version

21.0.98

### Mod Version

1.21-6.3.1.0

### Modpack or other Mod

[Craftoria](https://www.curseforge.com/minecraft/modpacks/craftoria/files/5541105)

### Describe the Issue

Postman hat uses `c:lapis` tag, when it doesn't exist, proper tag would be `c:gems/lapis`
![{D4A7C49B-A907-41FB-AF7A-1B375ADC8260}](https://github.com/user-attachments/assets/e0d295b9-8715-4490-9936-8e41ff54954d)
![{A56EE189-E25A-4F99-A836-B1AE7F9C241A}](https://github.com/user-attachments/assets/2288b8f4-1ed3-4149-b44f-35135162c6fd)
![{73390530-39E2-4CF8-BB6C-0FDEB6DF7570}](https://github.com/user-attachments/assets/acce02ed-7895-4bf0-9a9d-b2a3a570c764)

**Comment by cech12** [comment] 2024-07-18 16:45
Hey thanks for your report! I will look into that! :)

**Comment by cech12** [comment] 2024-07-18 17:19
Thanks for your report! The issue is fixed in the upcoming versions:
- 1.21-6.4.0.0
- 1.20.6-5.2.0.2

**Closed as completed by cech12** 2024-07-18 17:19 UTC
Labels: bug
