### ISSUE TITLE
[Bug]: Crashed when trying to pick hats on creative mode 1.21

### ISSUE THREAD

**Issue by makumaku1974** [cech12/UsefulHats#63] opened 2024-07-08 09:14 UTC
### Minecraft Version

1.21

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Mod Version

6.1.1.0

### Modpack or other Mod

Not quite sure about an error from another mod, also this is a custom modpack and unreleased.

### Describe the Issue

https://mclo.gs/P0fFOz2

### Logs

https://mclo.gs/nGhFuQ4

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Sodium, Modern Fixes, Immediately Fast, Nvidium.

**Comment by cech12** [comment] 2024-07-08 09:22
Thanks for your report! I will look into that when I have time :)

**Comment by cech12** [comment] 2024-07-08 09:23
@makumaku1974 Could you describe, what exactly you are doing to crash the game?

**Comment by makumaku1974** [comment] 2024-07-08 09:46
> @makumaku1974 Could you describe, what exactly you are doing to crash the game?
ill check it again.

**Comment by makumaku1974** [comment] 2024-07-08 09:54
> @makumaku1974 Could you describe, what exactly you are doing to crash the game?

I crashed when i hover over to the Straw Hat. Creative Mode

**Comment by cech12** [comment] 2024-07-08 16:17
I could not reproduce the issue, but I changed the way of getting the enchantment level for the item tooltip. So, I think the issue is fixed in the upcoming version 1.21-6.2.0.0.
If not, feel free to reopen the issue. Thanks again for your report! :)

**Closed as completed by cech12** 2024-07-08 16:17 UTC
Labels: bug

**Comment by makumaku1974** [comment] 2024-07-09 12:10
It works now. Maybe it has something to do with how loaded my modpack is... sorry :>
